### ISSUE TITLE
Parse with callback can't be cancelled

### ISSUE THREAD

**Issue by ObserverOfTime** [tree-sitter/java-tree-sitter#3]
The `parse(String)` method can be cancelled, but the `parse(ParseCallback)` method cannot.
Neither the timeout nor the cancellation flag work and I have no idea why.

**Comment by Sigma42** [comment]
I think cancelation works (on the current treesitter versions), and the problem is just the callback of the test(s). 

With a callback like:
https://github.com/tree-sitter/java-tree-sitter/blob/c3464e7dc20410d4af9b69484ff239d49f7666a7/src/test/java/io/github/treesitter/jtreesitter/ParserTest.java#L115
and a starting offset of `0` it will be `source.substring(0,0)` and that will always be `""`. 
Then treesitter interprets that as: 
* parsing is done
  * before any actual parsing step happens, so the cancelation flag and timeout never get checked. 
* sourcecode is empty
  * because Java's grammar accepts that as a 'program' node, both asserts succeeded https://github.com/tree-sitter/java-tree-sitter/blob/c3464e7dc20410d4af9b69484ff239d49f7666a7/src/test/java/io/github/treesitter/jtreesitter/ParserTest.java#L118-L119

If the callback reads, at least one byte each time it's called, it parses the file correctly, and it is canceled by flag and by timeout.
Examples (all of these tests succeed locally on my machine):
* [reading 1 byte each callback call](https://github.com/Sigma42/java-tree-sitter/blob/d1a2597dde0eb0a4d65b722bae4b9e84f5b9c60c/src/test/java/io/github/treesitter/jtreesitter/ParserTest.java#L109-L123)
* [reading full text in first callback call](https://github.com/Sigma42/java-tree-sitter/blob/d1a2597dde0eb0a4d65b722bae4b9e84f5b9c60c/src/test/java/io/github/treesitter/jtreesitter/ParserTest.java#L125-L138)
* [timeout while reading 1 byte each callback call](https://github.com/Sigma42/java-tree-sitter/blob/d1a2597dde0eb0a4d65b722bae4b9e84f5b9c60c/src/test/java/io/github/treesitter/jtreesitter/ParserTest.java#L148-L157)
* [timeout while reading full text in first callback call](https://github.com/Sigma42/java-tree-sitter/blob/d1a2597dde0eb0a4d65b722bae4b9e84f5b9c60c/src/test/java/io/github/treesitter/jtreesitter/ParserTest.java#L159-L167)
* [cancelation while reading 1 byte each callback call](https://github.com/Sigma42/java-tree-sitter/blob/d1a2597dde0eb0a4d65b722bae4b9e84f5b9c60c/src/test/java/io/github/treesitter/jtreesitter/ParserTest.java#L218-L244)
* [cancelation while reading full text in first callback call](https://github.com/Sigma42/java-tree-sitter/blob/d1a2597dde0eb0a4d65b722bae4b9e84f5b9c60c/src/test/java/io/github/treesitter/jtreesitter/ParserTest.java#L191-L216)
